### PR TITLE
minor change to initiate pull request

### PR DESCRIPTION
**Pull request by mayerstrk**
Sorry for the trouble i thought i would deploy to heroku so I pushed to main :(
I'll make sure to deploy to a prod build next time.
Thanks!!

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review, it already looks decent! I marked several issues below and hope that you can fix them easily and improve your project. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Modal window should have close button
    * Mismatches of the main page with the mockup on 1440px https://pasteboard.co/C8sS2uFLXmLv.png https://pasteboard.co/69hLweDcfRpB.png
    * Mismatches of the main page with the mockup on 768px https://pasteboard.co/01kylAZB62BL.png https://pasteboard.co/COlJezlowFp2.png https://pasteboard.co/cjQEddIbtffa.png
    * Mismatches of the main page with the mockup on 320px https://pasteboard.co/X35tgWilk2Eb.png
    * Mobile nav menu looks different from the mockup, please check the spaces and aligning of the items
    * Mismatches of the saved-articles page on 1440px https://pasteboard.co/3FRQqhjRmAlz.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Page components should keep its width on more than 1440px screen resolutions
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Links in footer should work properly
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Search form button should have hover and active states
    * Modal submit button should have default and disabled states, disabled button shouldn't have hover state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 60

**Comment by mayerstrk** [comment]
Screenshot from 2024-03-31 14-27-05
Screenshot from 2024-03-31 11-15-54

Tried to adjust it as much as I could but some of the things in this design just... yeah

**Comment by mayerstrk** [comment]
> Screenshot from 2024-03-31 14-27-05 Screenshot from 2024-03-31 11-15-54
> 
> Tried to adjust it as much as I could but some of the things in this design just... yeah

i also kept the Show more button in the saved articles gallery, i thought it was a cool feature :)

**Comment by FiLLa-FaS** [comment]
Hi! Great job - almost all issues were fixed! You've got more than 80 points, so I'm really happy to accept your project, Good luck on the next diploma stage!🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Links in footer should be opened in a new tab
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 87

**Pull request merged**
